### ISSUE TITLE
ステップのフォームを書き換えた結果既存のものとtitle,linkが一緒になったときエラーになる

### ISSUE THREAD

**Issue by pahalce** [Piko-Piko-Pon-Taro/navict-app#161]

**Comment by dubianhaozhi** [comment]
@pahalce どんなエラー？

**Comment by pahalce** [comment]
unique constraintのやつ

**Comment by pahalce** [comment]
とりあえず一回POSTしてエラー名キャッチしたらGETしようかな
ここの仕組み変わりそうだし

**Comment by dubianhaozhi** [comment]
そのエラー正しい挙動

**Comment by dubianhaozhi** [comment]
なのでそのエラー来たらcreateしないってしてほしい！

**Comment by pahalce** [comment]
createはしないんだけど、いまのtitle,link両方打ち込む実装だとステップ作るとき、
1. 毎回titleとlinkが両方一緒のものがDBにないか確認するためにリクエスト飛ばして、なければ作る
2. createしようとしてみてエラー帰ってきたらcreateせず既存のやつ使う
のどっちかにしないといけなさそうって感じ

**Comment by dubianhaozhi** [comment]
そもそも一文字目入力する時点でlibrary取ってきてるからtitle,link同じやつ作らないようにクライアントで制御できるくね？

**Comment by pahalce** [comment]
れこめんどのときtitle打ち込まないからできない

**Comment by pahalce** [comment]
レコメンドされたの選択して、そのあとでリンクだけ変えたとき

**Comment by dubianhaozhi** [comment]
あーなるほど

**Comment by dubianhaozhi** [comment]
createしてみてcatchがいいと思う

**Comment by pahalce** [comment]
ちょっと実装方法として違和感あるけど、いろんな事考えたらとりあえずそれが一番よさそうな気がするよね

**Comment by dubianhaozhi** [comment]
超細かいこと言うと、1だと、
getしてみてあったらcreateしない、なかったらcreateする
ってやってる間に他の人が作ったときに処理しきれないので

2だね🙆‍♂️

**Comment by pahalce** [comment]
あーそっか、なるほど
２のほうがいいのか

**Comment by pahalce** [comment]
やっぱりますますlinkだけuniqueにしてっていう実装のほうがいい気がしてくる

**Comment by dubianhaozhi** [comment]
いや、Libraryはlinkとtitleの複合uniqueでよくて、
Stepにtitleカラムを追加して、
ユーザーはStepのtitleとLibraryのlinkだけいじれて、
Libraryのtitleはlinkから自動取得にするのがいいと思ってる
今のところ。

**Comment by pahalce** [comment]
@dubianhaozhi　これupsertで解決したりする？

**Comment by dubianhaozhi** [comment]
する

**Comment by dubianhaozhi** [comment]
たしかにそのエラー返す必要無いからupsertで処理したほうがいいわ。
複合uniqueでupsertできるかわかんないからあとでやってみる

**Comment by dubianhaozhi** [comment]
@pahalce 
ここで対応しといた。
https://github.com/Piko-Piko-Pon-Taro/navict-app/pull/155/commits/e17b7233db87b3de23deb524828b8d94f4fbdd72

**Comment by pahalce** [comment]
あざす
