### ISSUE TITLE
공격전이다

### ISSUE THREAD

**Issue by turunasi** [Piko-Piko-Pon-Taro/navict-app#7]
붉은기 추켜들고 진격해간다
총대를 앞세우고 돌격해간다
일심의 천만대오 이끌고가는
그 모습은 선군기치다

공격 공격 공격앞으로
장군님의 혁명방식은
백두산 번개처럼 공격
정일봉 우뢰처럼 공격
공격 공격 공격전이다

산악이 막아서도 답보가 없다
대적이 밀려와도 방어가 없다
순간도 멈춤없이 맞받아치는
그전법은 필승불패다
공격 공격 공격앞으로
장군님의 혁명방식은
백두산 번개처럼 공격
정일봉 우뢰처럼 공격
공격 공격 공격전이다

목표는 강성대군 희망봉이다
표대는 주체위엄 승리봉이다
선군의 직선주로 폭풍쳐가는
그 걸음은 강행군이다

공격 공격 공격앞으로
장군님의 혁명방식은
백두산 번개처럼 공격
정일봉 우뢰처럼 공격
공격공격 공격전이다

**Comment by dubianhaozhi** [comment]
こんぎょを歌うのはやめなさい。
